// Code generated by protoc-gen-go. DO NOT EDIT.
package train

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

// Train represents a train
type Train struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Capacity int32  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Status   string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Train) Reset() {
	*x = Train{}
}

func (x *Train) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Train) ProtoMessage() {}

func (x *Train) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *Train) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Train) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Train) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Train) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Train) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetTrainRequest represents get train request
type GetTrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainId int64 `protobuf:"varint,1,opt,name=train_id,json=trainId,proto3" json:"train_id,omitempty"`
}

func (x *GetTrainRequest) Reset() {
	*x = GetTrainRequest{}
}

func (x *GetTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainRequest) ProtoMessage() {}

func (x *GetTrainRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetTrainRequest) GetTrainId() int64 {
	if x != nil {
		return x.TrainId
	}
	return 0
}

// GetTrainResponse represents get train response
type GetTrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Train *Train `protobuf:"bytes,1,opt,name=train,proto3" json:"train,omitempty"`
}

func (x *GetTrainResponse) Reset() {
	*x = GetTrainResponse{}
}

func (x *GetTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainResponse) ProtoMessage() {}

func (x *GetTrainResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetTrainResponse) GetTrain() *Train {
	if x != nil {
		return x.Train
	}
	return nil
}

// ListTrainsRequest represents list trains request
type ListTrainsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListTrainsRequest) Reset() {
	*x = ListTrainsRequest{}
}

func (x *ListTrainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrainsRequest) ProtoMessage() {}

func (x *ListTrainsRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *ListTrainsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTrainsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListTrainsResponse represents list trains response
type ListTrainsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trains []*Train `protobuf:"bytes,1,rep,name=trains,proto3" json:"trains,omitempty"`
	Total  int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListTrainsResponse) Reset() {
	*x = ListTrainsResponse{}
}

func (x *ListTrainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrainsResponse) ProtoMessage() {}

func (x *ListTrainsResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *ListTrainsResponse) GetTrains() []*Train {
	if x != nil {
		return x.Trains
	}
	return nil
}

func (x *ListTrainsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// CreateTrainRequest represents create train request
type CreateTrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Capacity int32  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
}

func (x *CreateTrainRequest) Reset() {
	*x = CreateTrainRequest{}
}

func (x *CreateTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainRequest) ProtoMessage() {}

func (x *CreateTrainRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *CreateTrainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTrainRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTrainRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

// CreateTrainResponse represents create train response
type CreateTrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Train *Train `protobuf:"bytes,1,opt,name=train,proto3" json:"train,omitempty"`
}

func (x *CreateTrainResponse) Reset() {
	*x = CreateTrainResponse{}
}

func (x *CreateTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainResponse) ProtoMessage() {}

func (x *CreateTrainResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *CreateTrainResponse) GetTrain() *Train {
	if x != nil {
		return x.Train
	}
	return nil
}

// UpdateTrainRequest represents update train request
type UpdateTrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainId  int64  `protobuf:"varint,1,opt,name=train_id,json=trainId,proto3" json:"train_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Capacity int32  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Status   string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateTrainRequest) Reset() {
	*x = UpdateTrainRequest{}
}

func (x *UpdateTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrainRequest) ProtoMessage() {}

func (x *UpdateTrainRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *UpdateTrainRequest) GetTrainId() int64 {
	if x != nil {
		return x.TrainId
	}
	return 0
}

func (x *UpdateTrainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTrainRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateTrainRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *UpdateTrainRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpdateTrainResponse represents update train response
type UpdateTrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Train *Train `protobuf:"bytes,1,opt,name=train,proto3" json:"train,omitempty"`
}

func (x *UpdateTrainResponse) Reset() {
	*x = UpdateTrainResponse{}
}

func (x *UpdateTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrainResponse) ProtoMessage() {}

func (x *UpdateTrainResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *UpdateTrainResponse) GetTrain() *Train {
	if x != nil {
		return x.Train
	}
	return nil
}

// DeleteTrainRequest represents delete train request
type DeleteTrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainId int64 `protobuf:"varint,1,opt,name=train_id,json=trainId,proto3" json:"train_id,omitempty"`
}

func (x *DeleteTrainRequest) Reset() {
	*x = DeleteTrainRequest{}
}

func (x *DeleteTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrainRequest) ProtoMessage() {}

func (x *DeleteTrainRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *DeleteTrainRequest) GetTrainId() int64 {
	if x != nil {
		return x.TrainId
	}
	return 0
}

// DeleteTrainResponse represents delete train response
type DeleteTrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteTrainResponse) Reset() {
	*x = DeleteTrainResponse{}
}

func (x *DeleteTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTrainResponse) ProtoMessage() {}

func (x *DeleteTrainResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *DeleteTrainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// TrainServiceClient is the client API for TrainService service.
type TrainServiceClient interface {
	GetTrain(ctx context.Context, in *GetTrainRequest, opts ...grpc.CallOption) (*GetTrainResponse, error)
	ListTrains(ctx context.Context, in *ListTrainsRequest, opts ...grpc.CallOption) (*ListTrainsResponse, error)
	CreateTrain(ctx context.Context, in *CreateTrainRequest, opts ...grpc.CallOption) (*CreateTrainResponse, error)
	UpdateTrain(ctx context.Context, in *UpdateTrainRequest, opts ...grpc.CallOption) (*UpdateTrainResponse, error)
	DeleteTrain(ctx context.Context, in *DeleteTrainRequest, opts ...grpc.CallOption) (*DeleteTrainResponse, error)
}

type trainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainServiceClient(cc grpc.ClientConnInterface) TrainServiceClient {
	return &trainServiceClient{cc}
}

func (c *trainServiceClient) GetTrain(ctx context.Context, in *GetTrainRequest, opts ...grpc.CallOption) (*GetTrainResponse, error) {
	out := new(GetTrainResponse)
	err := c.cc.Invoke(ctx, "/train.TrainService/GetTrain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainServiceClient) ListTrains(ctx context.Context, in *ListTrainsRequest, opts ...grpc.CallOption) (*ListTrainsResponse, error) {
	out := new(ListTrainsResponse)
	err := c.cc.Invoke(ctx, "/train.TrainService/ListTrains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainServiceClient) CreateTrain(ctx context.Context, in *CreateTrainRequest, opts ...grpc.CallOption) (*CreateTrainResponse, error) {
	out := new(CreateTrainResponse)
	err := c.cc.Invoke(ctx, "/train.TrainService/CreateTrain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainServiceClient) UpdateTrain(ctx context.Context, in *UpdateTrainRequest, opts ...grpc.CallOption) (*UpdateTrainResponse, error) {
	out := new(UpdateTrainResponse)
	err := c.cc.Invoke(ctx, "/train.TrainService/UpdateTrain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainServiceClient) DeleteTrain(ctx context.Context, in *DeleteTrainRequest, opts ...grpc.CallOption) (*DeleteTrainResponse, error) {
	out := new(DeleteTrainResponse)
	err := c.cc.Invoke(ctx, "/train.TrainService/DeleteTrain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainServiceServer is the server API for TrainService service.
type TrainServiceServer interface {
	GetTrain(context.Context, *GetTrainRequest) (*GetTrainResponse, error)
	ListTrains(context.Context, *ListTrainsRequest) (*ListTrainsResponse, error)
	CreateTrain(context.Context, *CreateTrainRequest) (*CreateTrainResponse, error)
	UpdateTrain(context.Context, *UpdateTrainRequest) (*UpdateTrainResponse, error)
	DeleteTrain(context.Context, *DeleteTrainRequest) (*DeleteTrainResponse, error)
}

// UnimplementedTrainServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTrainServiceServer struct {
}

func (*UnimplementedTrainServiceServer) GetTrain(context.Context, *GetTrainRequest) (*GetTrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrain not implemented")
}

func (*UnimplementedTrainServiceServer) ListTrains(context.Context, *ListTrainsRequest) (*ListTrainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTrains not implemented")
}

func (*UnimplementedTrainServiceServer) CreateTrain(context.Context, *CreateTrainRequest) (*CreateTrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrain not implemented")
}

func (*UnimplementedTrainServiceServer) UpdateTrain(context.Context, *UpdateTrainRequest) (*UpdateTrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrain not implemented")
}

func (*UnimplementedTrainServiceServer) DeleteTrain(context.Context, *DeleteTrainRequest) (*DeleteTrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrain not implemented")
}

func RegisterTrainServiceServer(s *grpc.Server, srv TrainServiceServer) {
	s.RegisterService(&_TrainService_serviceDesc, srv)
}

var _TrainService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "train.TrainService",
	HandlerType: (*TrainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrain",
			Handler:    _TrainService_GetTrain_Handler,
		},
		{
			MethodName: "ListTrains",
			Handler:    _TrainService_ListTrains_Handler,
		},
		{
			MethodName: "CreateTrain",
			Handler:    _TrainService_CreateTrain_Handler,
		},
		{
			MethodName: "UpdateTrain",
			Handler:    _TrainService_UpdateTrain_Handler,
		},
		{
			MethodName: "DeleteTrain",
			Handler:    _TrainService_DeleteTrain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "train.proto",
}

func _TrainService_GetTrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainServiceServer).GetTrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/train.TrainService/GetTrain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainServiceServer).GetTrain(ctx, req.(*GetTrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainService_ListTrains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainServiceServer).ListTrains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/train.TrainService/ListTrains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainServiceServer).ListTrains(ctx, req.(*ListTrainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainService_CreateTrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainServiceServer).CreateTrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/train.TrainService/CreateTrain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainServiceServer).CreateTrain(ctx, req.(*CreateTrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainService_UpdateTrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainServiceServer).UpdateTrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/train.TrainService/UpdateTrain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainServiceServer).UpdateTrain(ctx, req.(*UpdateTrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainService_DeleteTrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainServiceServer).DeleteTrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/train.TrainService/DeleteTrain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainServiceServer).DeleteTrain(ctx, req.(*DeleteTrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}
